---
kind: pipeline
type: docker
name: notify-pipeline-start

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      link_names: true
      template: >
        {{#if build.pull }}
          *Build started*: {{ repo.owner }}/{{ repo.name }}cc - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
          *Build started: {{ repo.owner }}/{{ repo.name }} - Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <{{ build.link }}|Visit build page ↗>